trainer:
    name: Biped
    min_steps: 48
    max_steps: 64
    visualize_output: true
    device_id: 0
    use_cuda: true
    num_hidden_channels: 10
    epochs: 20000
    batch_size: 5
    damage: true
    num_damaged: 2
    damage_radius_denominator: 3
    loss_threshold: 0.0
    #early_stoppage: false
    model_config:
        normal_std: 0.1
        update_net_channel_dims: [32, 32]
    optimizer_config:
        lr: 0.0002            
    dataset_config:
        pool_size: 32 

defaults:
    - voxel